# Generated by Django 5.2.7 on 2025-10-07 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateTimeField(auto_now_add=True)),
                ("fecha_devolucion", models.DateField(blank=True, null=True)),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="libros.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "ordering": ["-fecha_prestamo"],
            },
        ),
    ]
